<?php
 /**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * @category   Payment
 * @package    Arpalinks_Nextpay
 * @copyright  Copyright (c) 2017 Nextpay (http://www.nextpay.ir)
 */
?>

<fieldset class="form-list">
    <?php $_code=$this->getMethodCode() ?>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <?php echo $this->__('You will be redirected to Nextpay website when you place an order.') ?><br />
        </li>
        <div style="padding:10px 15px 15px;">
          <img src="<?php echo $this->getPaymentImageSrc(); ?>" alt="<?php echo $this->__('Nextpay payment methods') ?>" />
        </div>
    </ul>
</fieldset>
