<?php
 /**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * @category   Payment
 * @package    Arpalinks_Nextpay
 * @copyright  Copyright (c) 2017 Nextpay (http://www.nextpay.ir)
 */
?>

<style type="text/css">
.titr {
	font-family: Tahoma;
	font-size: 14px;
}
</style>
<center>
    <span class="titr"><b>در حال اتصال به نکست پی</b>
    <br />لطفا منتظر بمانید
    </span>
</center>
<form id="arpalinks_nextpay" action="<?php echo $this->getFormAction();?>" method="POST">
<?php if (is_array($this->getFormData())): ?>
    <?php foreach ($this->getFormData() as $name => $value): ?>
        <input type="hidden" name="<?php echo $name; ?>" value="<?php echo $value; ?>"/>
    <?php endforeach; ?>
<?php endif; ?>
</form>

<script type="text/javascript">
//<![CDATA[
    var paymentform = document.getElementById('arpalinks_nextpay');
    window.onload = paymentform.submit();
//]]>
</script>
