<?php
 /**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * @category   Payment
 * @package    Arpalinks_Nextpay
 * @copyright  Copyright (c) 2017 Nextpay (http://www.nextpay.ir)
 */
?>

<?php
	echo $this->getMethod()->getTitle() . '<br/>';
	if ($this->getInfo()->getLastTransId() == '') {
		echo $this->__('Payment has not been processed yet.') . '<br/>';
	} else {
		echo $this->__('Nextpay Transaction ID: %s', $this->htmlEscape($this->getInfo()->getLastTransId())) . '<br/>';
	}
?>
